###
#Setup 2 users
GET http://localhost:8080/setup
Accept: application/json

###
#get all
GET http://localhost:8080/getall
Accept: application/json

###
#find by firstname Bob
GET http://localhost:8080/findbyfirstname?firstname=Bob
Accept: application/json

###
#find by lastname Smith
GET http://localhost:8080/findbylastname?lastname=Smith
Accept: application/json

###
#update firstname Alice to Esther
PUT http://localhost:8080/update?firstname=Alice&newFirstname=Esther
Accept: application/json

###
#add article to Bob
PUT http://localhost:8080/addarticle?firstname=Bob&type=computer&prize=1019.90
Accept: application/json

###
#delete by lastname
DELETE http://localhost:8080/delete?lastname=Smith
Accept: application/json